<?php

/**
 * @file
 * Functions to support theming in the Olivero theme.
 */

/**
 * Implements hook_theme().
 */
function studentregistration_theme($existing, $type, $theme, $path) {
  return [
    'studentregistration_result' => [
      'variables' => [
        'name' => NULL,
        'email' => NULL,
        'id' => NULL,
        'rollnumner' => NULL,
        'phone' => NULL,
        'dob' => NULL,
        'gender' => NULL,
        'average_mark' => NULL,
      ],
    ],
    'studentregistration_list' => [
      'variables' => [
        'students' => NULL,
      ],
    ],
  ];
}
