# Schema for the configuration files of the random_color_blocks module.
random_color_blocks.settings:
  type: config_object
  label: 'Plugin random_color_blocks settings'
  mapping:
    example:
      type: string
      label: 'Example'
    block_count:
      type: integer
      label: 'Block count.'
